- name: setup frontend
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
       name: nginx
       state: present

    - name: place expense config file in nginx
      ansible.builtin.copy:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf

    - name: remove old content
      ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent

    - name: creating nginx content directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and extract frontend data
      ansible.builtin.unarchive:
         src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
         dest: /usr/share/nginx/html
         remote_src: yes

    - name: start nginx service
      ansible.builtin.systemd:
       name: nginx
       state: restarted
       enabled: yes









