- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: place expense config file in nginx
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: include app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_form: app_prereq


- name: start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes